[package]
name = "cheesecloth-rust-example-secrets"
version = "0.1.0"
authors = ["Stuart Pernsteiner <spernsteiner@galois.com>"]
edition = "2018"

[dependencies]
cheesecloth-rust-example-secret-decls = { path = "../secret-decls" }

[features]
microram = []

[lib]
path = "lib.rs"

[[bin]]
name = "secrets"
path = "main.rs"
